"""jia

Revision ID: 01da6e7b904d
Revises: 2a034520d120
Create Date: 2020-06-10 08:56:53.325397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01da6e7b904d'
down_revision = '2a034520d120'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_column('meettimese')

    with op.batch_alter_table('insurancese', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bxzeren', sa.Text(), nullable=True))
        batch_op.drop_column('nextgetmoney')

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['phnumber'])
        batch_op.drop_column('insurance')
        batch_op.drop_column('families')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('families', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('insurance', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('insurancese', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nextgetmoney', sa.INTEGER(), nullable=True))
        batch_op.drop_column('bxzeren')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meettimese', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
