"""客户明细家人和跟进改为客户等级和描述

Revision ID: 14b65ff5a74a
Revises: 7109dde6dd39
Create Date: 2020-06-09 09:09:05.015470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14b65ff5a74a'
down_revision = '7109dde6dd39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('grade', sa.String(length=64), nullable=True))
    op.add_column('posts', sa.Column('gradeintro', sa.String(length=64), nullable=True))
    op.create_unique_constraint(None, 'posts', ['phnumber'])
    op.drop_column('posts', 'families')
    op.drop_column('posts', 'insurance')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('insurance', sa.INTEGER(), nullable=True))
    op.add_column('posts', sa.Column('families', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'posts', type_='unique')
    op.drop_column('posts', 'gradeintro')
    op.drop_column('posts', 'grade')
    # ### end Alembic commands ###
