"""拜访情况修改

Revision ID: 95c99eef7d5d
Revises: 14b65ff5a74a
Create Date: 2020-06-09 12:59:23.357408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95c99eef7d5d'
down_revision = '14b65ff5a74a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'posts', ['phnumber'])
    op.drop_column('posts', 'insurance')
    op.drop_column('posts', 'families')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('families', sa.INTEGER(), nullable=True))
    op.add_column('posts', sa.Column('insurance', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'posts', type_='unique')
    # ### end Alembic commands ###
