"""添加客户出生年月

Revision ID: 98dbf6af31d8
Revises: 5633a7229963
Create Date: 2020-06-07 18:33:10.919940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98dbf6af31d8'
down_revision = '5633a7229963'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('old', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'posts', ['phnumber'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='unique')
    op.drop_column('posts', 'old')
    # ### end Alembic commands ###
