"""ee

Revision ID: b1fc25fbeb2f
Revises: 0cb39fb83184
Create Date: 2020-06-07 14:11:18.342457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1fc25fbeb2f'
down_revision = '0cb39fb83184'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'posts', ['phnumber'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='unique')
    # ### end Alembic commands ###
